DROP TABLE IF EXISTS `hello`;
CREATE TABLE `hello` (
  `ID` bigint NOT NULL COMMENT 'ID',
  `name` varchar(255) DEFAULT NULL COMMENT 'name',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT COMMENT='hello';
